manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson/zmk/tree/core/peripheral-behavior-invocation
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
